import os
import yaml
import shutil
from pathlib import Path

# === 🔄 已经全部替换为 autopdeagent ===
from autopdeagent.environments.local import LocalEnvironment
from autopdeagent.models.litellm_model import LitellmModel
from autopdeagent import package_dir
from autopdeagent.agents.pde_orchestrator import PDEOrchestrator

def main():
    print("🚀 Starting AutoPDEAgent Minimal Test...")

    # 1. 准备测试工作目录 (物理隔离)
    test_workspace = Path(os.getcwd()) / "test_workspace"
    if test_workspace.exists():
        shutil.rmtree(test_workspace)
    test_workspace.mkdir(parents=True)
    
    # 2. 加载基础配置和 Prompt
    default_config_path = package_dir / "config" / "default.yaml"
    task_prompts_path = package_dir / "config" / "pde_task_prompts.yaml"

    if not default_config_path.exists() or not task_prompts_path.exists():
        print("❌ Error: Could not find config yaml files. Please ensure they exist in src/autopdeagent/config/")
        return

    full_default_yaml = yaml.safe_load(default_config_path.read_text())
    base_agent_config = full_default_yaml.get("agent", {})
    
    runtime_common_config = {
        **base_agent_config,
        "mode": "yolo",       # 自动执行模式，不需要人类按回车确认
        "confirm_exit": False,
        "quiet": True
    }

    # 3. 构造极简测试 Prompt
    # 不做复杂的 PDE 数学题，只测试基础的文件读写和命令执行能力
    dummy_task = """
    This is a system integration test.
    Please do exactly the following steps:
    1. Write a Python script named `solver.py` that prints the exact phrase: "AutoPDEAgent is alive and working!"
    2. Run `python solver.py` to verify it works.
    3. Finish the task.
    """

    original_cwd = os.getcwd()

    try:
        # 切入工作目录
        os.chdir(test_workspace)
        print(f"📂 Switched to working directory: {test_workspace}")

        # 4. 初始化模型与环境
        # 注意：这里默认使用 gpt-4o，请确保你在终端 export 了 OPENAI_API_KEY
        print("🧠 Initializing DeepSeek Model and Environment...")
        
        # LiteLLM 原生支持 DeepSeek，只需要加上 'deepseek/' 前缀
        # 如果你想用专门写代码的模型，可以改成 "deepseek/deepseek-coder"
        model_obj = LitellmModel(
            model_name="deepseek/deepseek-chat", 
            cost_tracking="ignore_errors" # DeepSeek 的计费可能不在 LiteLLM 默认表里，忽略计费报错
        ) 
        env = LocalEnvironment()

        # 5. 启动编排器
        orchestrator = PDEOrchestrator(
            model=model_obj,
            env=env,
            base_config=runtime_common_config,
            task_prompts_path=task_prompts_path
        )

        print("\n=================== AGENT START ===================")
        exit_status, final_result = orchestrator.run(dummy_task)
        print("=================== AGENT END =====================\n")

        # 6. 验证结果
        if exit_status == "Submitted":
            print(f"✅ Success! Agent exited normally.")
            if Path("solver.py").exists():
                print("📄 Found solver.py generated by Agent. Content:")
                print(Path("solver.py").read_text())
            else:
                print("⚠️ Warning: Agent finished but solver.py was not found.")
        else:
            print(f"❌ Failed! Status: {exit_status}")
            print(f"Details: {final_result}")

    except Exception as e:
        import traceback
        print(f"🔥 Fatal Error: {e}")
        traceback.print_exc()
    finally:
        os.chdir(original_cwd)

if __name__ == "__main__":
    main()